import { requireUserId } from "@/lib/auth";
import { db } from "@/lib/db";
import { getWorkspaceByClerkUserId } from "@/lib/workspace";

export const dynamic="force-dynamic";

export default async function BillingPage(){
 const userId=await requireUserId(); const workspace=await getWorkspaceByClerkUserId(userId); const sub=await db.subscription.findUnique({where:{workspaceId:workspace.id}});
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">P</span> PayFlow</div><nav><a href="/dashboard">Overview</a><a href="/dashboard/invoices">Invoices</a><a href="/dashboard/clients">Clients</a><a href="/dashboard/follow-ups">Follow-ups</a></nav><div className="sidebar-bottom"><a href="/dashboard/settings">Settings</a><span className="secure-note">Private workspace</span></div></aside><section className="dashboard-page"><header className="dashboard-header"><div><div className="eyebrow">BILLING</div><h1>Choose your pace.</h1><p>Your plan belongs to your private workspace.</p></div><a className="secondary" href="/pricing">View public pricing</a></header><section className="settings-grid">{[{name:"Free",price:"$0",copy:"Start tracking invoices and follow-ups.",features:["5 active clients","Invoice tracking","Manual follow-ups"]},{name:"Pro",price:"$9/mo",copy:"Add automation as your workflow grows.",features:["More clients","Automated reminders","Payment workflow tools"]},{name:"Business",price:"$19/mo",copy:"For higher-volume solo operators.",features:["Higher limits","Advanced automation","Expanded controls"]}].map(p=><div className="panel" key={p.name}><div className="eyebrow">{p.name.toUpperCase()}</div><h2>{p.price}</h2><p>{p.copy}</p><ul className="plan-list">{p.features.map(f=><li key={f}>{f}</li>)}</ul><a className={sub?.plan===p.name.toUpperCase()?"primary":"secondary"} href="/pricing">{sub?.plan===p.name.toUpperCase()?"Current plan":"Choose plan"}</a></div>)}</section><div className="legal-notice">Stripe checkout and subscription activation are intentionally gated until the production Stripe account and webhook secret are configured. No payment is collected from this screen yet.</div></section></main>
}
