"use client";

import { FormEvent, useEffect, useState } from "react";
type Client={id:string;name:string;email?:string|null;company?:string|null};

export default function ClientsPage(){
 const [clients,setClients]=useState<Client[]>([]); const [message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/clients");if(r.ok)setClients((await r.json()).clients)}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/clients",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),email:f.get("email"),company:f.get("company")})});if(!r.ok){setMessage("Please check the client details.");return}e.currentTarget.reset();setMessage("Client added.");load()}
 async function remove(id:string){if(!confirm("Remove this client? Clients with invoices cannot be removed."))return;const r=await fetch("/api/clients/"+id,{method:"DELETE"});if(r.ok){setMessage("Client removed.");load()}else setMessage("Could not remove client.")}
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">P</span> PayFlow</div><nav><a href="/dashboard">Overview</a><a href="/dashboard/invoices">Invoices</a><a className="active" href="/dashboard/clients">Clients</a><a href="/dashboard/follow-ups">Follow-ups</a></nav><div className="sidebar-bottom"><a href="/dashboard/settings">Settings</a><span className="secure-note">Private workspace</span></div></aside><section className="dashboard-page"><header className="dashboard-header"><div><div className="eyebrow">CLIENTS</div><h1>Your client book.</h1><p>Simple records, kept inside your private workspace.</p></div><a className="secondary" href="/dashboard">Back to overview</a></header><section className="panel"><div className="panel-head"><div><h2>Add client</h2><p>No customer data is shared across accounts.</p></div></div><form className="form-grid" onSubmit={create}><label>Name<input name="name" required maxLength={120} placeholder="John Smith"/></label><label>Email<input name="email" type="email" maxLength={254} placeholder="john@example.com"/></label><label>Company<input name="company" maxLength={160} placeholder="Smith Studio"/></label><button className="primary" type="submit">Add client</button>{message&&<span className="form-message">{message}</span>}</form></section><section className="panel"><div className="panel-head"><div><h2>Clients</h2><p>{clients.length} client{clients.length===1?"":"s"}.</p></div></div><div className="table">{clients.length===0?<div className="empty-state"><strong>No clients yet.</strong><span>Add a client before creating an invoice.</span></div>:clients.map(c=><div className="table-row" key={c.id}><div className="client"><span className="avatar">{c.name[0]?.toUpperCase()??"C"}</span><div><strong>{c.name}</strong><small>{c.email||c.company||"No extra details"}</small></div></div><span>{c.company||"—"}</span><button className="follow" onClick={()=>remove(c.id)}>Remove</button></div>)}</div></section></section></main>
}
